import Head from "next/head";
import { getSession } from "next-auth/react";
import { Box } from "@mui/material";

export default function Home() {
  return (
    <>
      <Head>
        <title>Attensam</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}

export const getServerSideProps = async (context) => {
  const session = await getSession(context);

  if (!session) {
    return {
      redirect: {
        destination: "/auth/login",
        permanent: false,
      },
    };
  }
  return {
    props: { session },
    redirect: {
      destination: "/mobile-bookings",
      permanent: false,
    },
  };
};
