export const modalStyles = {
  protocolModal: {
    cardStyle: {
      position: "absolute",
      top: "50%",
      left: "50%",
      transform: "translate(-50%, -50%)",
      width: 550,
      height: 500,
      bgcolor: "background.paper",
      border: "2px solid #000",
      boxShadow: 24,
      p: 2,
      overflow: "auto",
      display: "flex",
      flexDirection: "column",
      placeItems: "space-between",
      paddingBottom: 0,
    },
    content: {
      display: "flex",
      flexDirection: "column",
      rowGap: "8px",
      justifyContent: "space-between",
      width: "100%",
      height: "100%",
    },
    button: {
      // backgroundColor: "secondary",
      width: "50%",
    },
  },
  bookingModal: {
    cardStyle: {
      position: "absolute",
      top: "50%",
      left: "50%",
      transform: "translate(-50%, -50%)",
      width: 550,
      height: 550,
      bgcolor: "background.paper",
      border: "2px solid #000",
      boxShadow: 24,
      p: 2,
      overflow: "auto",
      display: "grid",
      placeItems: "center",
    },
    content: {
      display: "flex",
      flexDirection: "column",
      rowGap: "8px",
      justifyContent: "center",
      width: "100%",
    },
    imgStyle: {
      backgroundPosition: "center",
      backgroundSize: "cover",
      height: "15rem",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: "10rem",
      color: "#00000055",
      backgroundColor: "#ddd",
    },
    inputGroup: {
      width: "100%",
      display: "flex",
      flexDirection: "column",
      justifyContent: "center",
      alignItems: "center",
      rowGap: "8px",
    },
    input: {
      border: "2px solid red",
      color: "red",
      height: "2rem",
      display: "none",
    },
    text: {
      padding: "10px 15px",
    },
    button: {
      // backgroundColor: "secondary",
      width: "45%",
    },
  },
  userModal: {
    cardStyle: {
      position: "absolute",
      top: "50%",
      left: "50%",
      transform: "translate(-50%, -50%)",
      width: 450,
      bgcolor: "background.paper",
      border: "2px solid #000",
      boxShadow: 24,
      padding: "0 1rem 1rem 1rem",
      overflow: "auto",
      height: 600,
      display: "flex",
      flexDirection: "column",
      justifyContent: "space-between",
    },
    content: {
      display: "flex",
      flexDirection: "column",
      justifyContent: "center",
      rowGap: "8px",
      paddingInline: 0,
      // paddingTop: 5,
    },
    imgStyle: {
      backgroundPosition: "center center",
      backgroundSize: "cover",
      backgroundRepeat: "no-repeat",
      height: "15rem",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: "7rem",
      color: "#00000055",
      backgroundColor: "#ddd",
    },
    inputGroup: {
      width: "100%",
      display: "flex",
      flexDirection: "column",
      justifyContent: "center",
      alignItems: "center",
      rowGap: "8px",
    },
    input: {
      // border: "2px solid red",
      color: "red",
      height: "2rem",
      display: "none",
    },

    text: {
      padding: "10px 15px",
    },
    button: {
      bgcolor: "secondary.main",
      width: "100%",
    },
  },
  errorModal: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    width: 400,
    bgcolor: "background.paper",
    border: "2px solid #000",
    boxShadow: 24,
    p: 4,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
};
